### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by richtrunzo** [richtrunzo/driving-game#2]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML Skeleton 
- [x] Add a car icon to Html
- [x] Add CSS styling
- [x] Test code for functionality
- [x] Remove all bugs
- [x] Remove CSS that has no affect
