### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by richtrunzo** [richtrunzo/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a data model that includes which way the car is facing, (north, south, east, or west).
- [x] Listen for 'keydown' events on the document.
- [x] Test code for functionality
- [x] Remove all bugs
- [x] Remove CSS that has no affect
