### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by richtrunzo** [richtrunzo/driving-game#4]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to the data model to hold the car's x and y coordinates on the page.
- [x] Use absolute positioning for the car image.
- [x] Use the style property of element objects to change the car's top and left box offset styles.
- [x] Move the car every 16 milliseconds for a smooth movement.
- [x] Test code for functionality
- [x] Remove all bugs
- [x] Remove CSS that has no affect
