### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by richtrunzo** [richtrunzo/driving-game#5]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean value to the data model to check if the car is started or stopped
- [x] Add an event lister for the spacebar that corresponds to the boolean value in the data model
- [x] Test code for functionality
- [x] Remove all bugs
- [x]  Remove CSS that has no affect
