### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by richtrunzo** [richtrunzo/driving-game#6]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Ensure that the keydown events for changing the cars direction work when it's started. 
- [x] Test code for functionality
- [x] Remove all bugs
- [x] Remove CSS that has no affect
